[package]
name = "hello-audio"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m-rt = "0.7"
panic-halt = "0.2.0"
#microbit-v2 = "0.13.0"
microbit-v2 = { path = "/local/src/old/microbit/microbit-v2" }


